package  SWF::Editor::Utils::Tag;
use strict;
use warnings;

use SWF::Editor::Tag;
use Exporter::Lite;
use Carp ();

our @EXPORT = qw/
    compare_tag_number
    get_tag_name
    get_tag_number
/;

our $TAG_NUMBER = {
    End                          => 0,
    ShowFrame                    => 1,
    DefineShape                  => 2,
    FreeCharacter                => 3,
    PlaceObject                  => 4,
    RemoveObject                 => 5,
    DefineBits                   => 6,
    DefineButton                 => 7,
    JPEGTables                   => 8,
    SetBackgroundColor           => 9,
    DefineFont                   => 10,
    DefineText                   => 11,
    DoAction                     => 12,
    DefineFontInfo               => 13,
    DefineSound                  => 14,
    StartSound                   => 15,
    StopSound                    => 16,
    DefineButtonSound            => 17,
    SoundStreamHead              => 18,
    SoundStreamBlock             => 19,
    DefineBitsLossless           => 20,
    DefineBitsJPEG2              => 21,
    DefineShape2                 => 22,
    DefineButtonCxform           => 23,
    Protect                      => 24,
    PathsArePostscript           => 25,
    PlaceObject2                 => 26,
    RemoveObject2                => 28,
    SyncFrame                    => 29,
    FreeAll                      => 31,
    DefineShape3                 => 32,
    DefineText2                  => 33,
    DefineButton2                => 34,
    DefineBitsJPEG3              => 35,
    DefineBitsLossless2          => 36,
    DefineEditText               => 37,
    DefineVideo                  => 38,
    DefineSprite                 => 39,
    NameCharacter                => 40,
    ProductInfo                  => 41,
    DefineTextFormat             => 42,
    FrameLabel                   => 43,
    SoundStreamHead2             => 45,
    DefineMorphShape             => 46,
    GenerateFrame                => 47,
    DefineFont2                  => 48,
    GeneratorCommand             => 49,
    DefineCommandObject          => 50,
    CharacterSet                 => 51,
    ExternalFont                 => 52,
    ExportAssets                 => 56,
    ImportAssets                 => 57,
    EnableDebugger               => 58,
    DoInitAction                 => 59,
    DefineVideoStream            => 60,
    VideoFrame                   => 61,
    DefineFontInfo2              => 62,
    DebugID                      => 63,
    EnableDebugger2              => 64,
    ScriptLimits                 => 65,
    SetTabIndex                  => 66,
    FileAttributes               => 69,
    PlaceObject3                 => 70,
    ImportAssets2                => 71,
    DefineFontAlignZones         => 73,
    CSMTextSettings              => 74,
    DefineFont3                  => 75,
    SymbolClass                  => 76,
    Metadata                     => 77,
    DefineScalingGrid            => 78,
    DoABC                        => 82,
    DefineShape4                 => 83,
    DefineMorphShape2            => 84,
    DefineSceneAndFrameLabelData => 86,
    DefineBinaryData             => 87,
    DefineFontName               => 88,
    StartSound2                  => 89,
    DefineBitsJPEG4              => 90,
    DefineFont4                  => 91,
};

our $TAG_NAME = {
    0 => 'End',
    1 => 'ShowFrame',
    2 => 'DefineShape',
    3 => 'FreeCharacter',
    4 => 'PlaceObject',
    5 => 'RemoveObject',
    6 => 'DefineBits',
    7 => 'DefineButton',
    8 => 'JPEGTables',
    9 => 'SetBackgroundColor',
    10 => 'DefineFont',
    11 => 'DefineText',
    12 => 'DoAction',
    13 => 'DefineFontInfo',
    14 => 'DefineSound',
    15 => 'StartSound',
    16 => 'StopSound',
    17 => 'DefineButtonSound',
    18 => 'SoundStreamHead',
    19 => 'SoundStreamBlock',
    20 => 'DefineBitsLossless',
    21 => 'DefineBitsJPEG2',
    22 => 'DefineShape2',
    23 => 'DefineButtonCxform',
    24 => 'Protect',
    25 => 'PathsArePostscript',
    26 => 'PlaceObject2',
    28 => 'RemoveObject2',
    29 => 'SyncFrame',
    31 => 'FreeAll',
    32 => 'DefineShape3',
    33 => 'DefineText2',
    34 => 'DefineButton2',
    35 => 'DefineBitsJPEG3',
    36 => 'DefineBitsLossless2',
    37 => 'DefineEditText',
    38 => 'DefineVideo',
    39 => 'DefineSprite',
    40 => 'NameCharacter',
    41 => 'ProductInfo',
    42 => 'DefineTextFormat',
    43 => 'FrameLabel',
    45 => 'SoundStreamHead2',
    46 => 'DefineMorphShape',
    47 => 'GenerateFrame',
    48 => 'DefineFont2',
    49 => 'GeneratorCommand',
    50 => 'DefineCommandObject',
    51 => 'CharacterSet',
    52 => 'ExternalFont',
    56 => 'ExportAssets',
    57 => 'ImportAssets',
    58 => 'EnableDebugger',
    59 => 'DoInitAction',
    60 => 'DefineVideoStream',
    61 => 'VideoFrame',
    62 => 'DefineFontInfo2',
    63 => 'DebugID',
    64 => 'EnableDebugger2',
    65 => 'ScriptLimits',
    66 => 'SetTabIndex',
    69 => 'FileAttributes',
    70 => 'PlaceObject3',
    71 => 'ImportAssets2',
    73 => 'DefineFontAlignZones',
    74 => 'CSMTextSettings',
    75 => 'DefineFont3',
    76 => 'SymbolClass',
    77 => 'Metadata',
    78 => 'DefineScalingGrid',
    82 => 'DoABC',
    83 => 'DefineShape4',
    84 => 'DefineMorphShape2',
    86 => 'DefineSceneAndFrameLabelData',
    87 => 'DefineBinaryData',
    88 => 'DefineFontName',
    89 => 'StartSound2',
    90 => 'DefineBitsJPEG4',
    91 => 'DefineFont4',
};
sub compare_tag_number {
    my ( $tag_number, $tag_name ) = @_;
    my $correct_tag_number = get_tag_number($tag_name);
    return $correct_tag_number == $tag_number;
}

sub get_tag_name {
    my $tag_number = shift;
    Carp::confess("Tag name does not passed!") unless defined $tag_number;
    return $TAG_NAME->{$tag_number};
}

sub get_tag_number {
    my $tag_name = shift;
    Carp::confess("Tag name does not passed!") unless defined $tag_name;
    Carp::confess("Tag $tag_name does not exists!") unless defined $TAG_NUMBER->{$tag_name};
    return $TAG_NUMBER->{$tag_name};
}

